# Generated by Django 3.2.13 on 2022-06-17 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='nmae',
            new_name='name',
        ),
    ]
