# Generated by Django 3.2.13 on 2022-06-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_rename_nmae_movie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='dddd', upload_to='', verbose_name='photos'),
            preserve_default=False,
        ),
    ]
